#!/usr/bin/env python3
"""
OpenSnek Setup Wizard
=====================
Interactive CLI that generates the .env configuration file.

Usage:
    python scripts/setup_wizard.py

This wizard collects:
1. University name
2. Azure AD credentials (for SSO)
3. LLM provider configuration
4. Database credentials (with sensible defaults)

Then writes a complete .env file.
"""

import os
import secrets
import sys
from pathlib import Path


def banner():
    print()
    print("=" * 60)
    print("  OpenSnek Setup Wizard")
    print("  AI-Powered University Learning Platform")
    print("=" * 60)
    print()


def prompt(label: str, default: str = "", secret: bool = False) -> str:
    """Prompt the user for input with an optional default."""
    if default:
        display = f"{label} [{default}]: "
    else:
        display = f"{label}: "

    if secret and default:
        display = f"{label} [{'*' * min(len(default), 8)}]: "

    value = input(display).strip()
    return value if value else default


def generate_secret() -> str:
    """Generate a URL-safe random secret."""
    return secrets.token_urlsafe(32)


def main():
    banner()

    project_root = Path(__file__).parent.parent
    env_path = project_root / ".env"

    if env_path.exists():
        overwrite = input(
            ".env file already exists. Overwrite? [y/N]: "
        ).strip().lower()
        if overwrite != "y":
            print("Aborted. Existing .env file preserved.")
            sys.exit(0)

    print("--- University Configuration ---")
    print()
    university_name = prompt("University name", "University")

    print()
    print("--- Azure AD / Microsoft Entra ID ---")
    print("Create an App Registration in Azure Portal:")
    print("  Azure Active Directory → App registrations → New registration")
    print("  Redirect URI: http://localhost:3782/api/auth/callback/microsoft-entra-id")
    print()
    azure_tenant = prompt("Azure AD Tenant ID")
    azure_client = prompt("Azure AD Client ID")
    azure_secret = prompt("Azure AD Client Secret", secret=True)

    print()
    print("--- LLM Configuration ---")
    print("Choose your LLM provider:")
    print("  1. OpenAI (gpt-4o)")
    print("  2. Anthropic (claude-3-5-sonnet)")
    print("  3. Ollama (local, free)")
    print("  4. Custom")
    print()
    llm_choice = prompt("Provider", "1")

    llm_binding = "openai"
    llm_model = "gpt-4o"
    llm_key = ""
    llm_host = "https://api.openai.com/v1"

    if llm_choice == "1":
        llm_binding = "openai"
        llm_model = prompt("Model name", "gpt-4o")
        llm_key = prompt("OpenAI API key", secret=True)
        llm_host = "https://api.openai.com/v1"
    elif llm_choice == "2":
        llm_binding = "anthropic"
        llm_model = prompt("Model name", "claude-3-5-sonnet")
        llm_key = prompt("Anthropic API key", secret=True)
        llm_host = "https://api.anthropic.com"
    elif llm_choice == "3":
        llm_binding = "ollama"
        llm_model = prompt("Model name", "llama3")
        llm_host = prompt("Ollama URL", "http://host.docker.internal:11434")
        llm_key = "not-needed"
    else:
        llm_binding = prompt("LLM binding")
        llm_model = prompt("Model name")
        llm_key = prompt("API key", secret=True)
        llm_host = prompt("API host URL")

    print()
    print("--- Embedding Configuration ---")
    embed_binding = prompt("Embedding provider", "openai")
    embed_model = prompt("Embedding model", "text-embedding-3-small")
    embed_key = prompt("Embedding API key (or same as LLM)", llm_key, secret=True)
    embed_host = prompt("Embedding host", "https://api.openai.com/v1")
    embed_dim = prompt("Embedding dimensions", "3072")

    print()
    print("--- Database Configuration (defaults work with Docker) ---")
    pg_user = prompt("PostgreSQL user", "opensnek")
    pg_pass = prompt("PostgreSQL password", "opensnek_secret", secret=True)
    pg_port = prompt("PostgreSQL port", "5432")
    redis_port = prompt("Redis port", "6379")

    print()
    print("--- Ports ---")
    backend_port = prompt("Backend API port", "8001")
    frontend_port = prompt("Frontend port", "3782")

    # Generate NextAuth secret
    nextauth_secret = generate_secret()

    # Build .env content
    env_content = f"""# ============================================
# OpenSnek Configuration
# Generated by setup_wizard.py
# ============================================

# University
UNIVERSITY_NAME={university_name}

# Server Ports
BACKEND_PORT={backend_port}
FRONTEND_PORT={frontend_port}

# LLM Configuration
LLM_BINDING={llm_binding}
LLM_MODEL={llm_model}
LLM_API_KEY={llm_key}
LLM_HOST={llm_host}

# Embedding Configuration
EMBEDDING_BINDING={embed_binding}
EMBEDDING_MODEL={embed_model}
EMBEDDING_API_KEY={embed_key}
EMBEDDING_HOST={embed_host}
EMBEDDING_DIMENSION={embed_dim}

# Azure AD / Microsoft Entra ID
AZURE_AD_TENANT_ID={azure_tenant}
AZURE_AD_CLIENT_ID={azure_client}
AZURE_AD_CLIENT_SECRET={azure_secret}

# NextAuth.js (auto-generated, do not change)
NEXTAUTH_SECRET={nextauth_secret}
NEXTAUTH_URL=http://localhost:{frontend_port}
AUTH_TRUST_HOST=true

# PostgreSQL
POSTGRES_USER={pg_user}
POSTGRES_PASSWORD={pg_pass}
POSTGRES_PORT={pg_port}

# Redis
REDIS_PORT={redis_port}

# Optional: TTS, Search, etc.
# TTS_BINDING=openai
# TTS_MODEL=tts-1
# TTS_API_KEY=
# TTS_URL=https://api.openai.com/v1
# TTS_VOICE=alloy
# SEARCH_PROVIDER=perplexity
# SEARCH_API_KEY=
"""

    with open(env_path, "w") as f:
        f.write(env_content)

    print()
    print("=" * 60)
    print(f"  .env file written to: {env_path}")
    print("=" * 60)
    print()
    print("Next steps:")
    print(f"  1. docker compose up -d")
    print(f"  2. Open http://localhost:{frontend_port}")
    print(f"  3. Sign in with your Microsoft account")
    print()
    print(f"  Enrollment codes are generated when professors create courses.")
    print(f"  To make a user a professor, use the admin API or database.")
    print()


if __name__ == "__main__":
    main()
